language: php

php:
  - 5.3
  - 5.4
  - 5.5

script:
  - phpunit --coverage-clover build/logs/clover.xml

install:
  - composer require --dev satooshi/php-coveralls:dev-master
  - composer install

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database `test-jam-freezable`;'
  - mysql --default-character-set=utf8 test-jam-freezable < tests/test_data/structure.sql

after_script:
  - php vendor/bin/coveralls -v
